### ISSUE TITLE
Package will not update in Forge VTT

### ISSUE THREAD

**Issue by theMagius0** [lipefl/sync-token-name#11]
Failure when trying to update to version 1.0.5 in Forge VTT.

No error message _specifics_ are displayed.

My Foundry VTT version is v11 Build 308.

Pic attached.

![SyncTokenNamesFailure](https://github.com/lipefl/sync-token-name/assets/85370867/88d57bab-924d-41ee-993c-e0748242065a)

**Comment by lipefl** [comment]
Maybe it was because i didn't update it in Foundry modules list. It's updated now.
Can you re-check? If it doesn't work, i suggest you uninstall and install again using foundry interface, if possible (i'm not familiar with Forge VTT)

**Comment by theMagius0** [comment]
That worked.

Thx for the quick update.
