### ISSUE TITLE
Pathfinder 2e system support?

### ISSUE THREAD

**Issue by Janonas** [lipefl/sync-token-name#6]
As of now, this module doesnt work with the Pathfinder 2nd edition system. tested without other modules.

**Comment by lipefl** [comment]
Hi, I tested with Pathfinder 2 and it's working. Be sure everything is updated. If you still have problems, try looking at the console (F12) to see if there are errors. And/or send some screenshots to show the problem.

Tested with
Foundry 10.287
Pathfinder 2nd 4.2.4

**Comment by Janonas** [comment]
Ah i was expecting it to affect already placed tokens when renaming, while it only does newly placed tokens. So thats where the confusion came from
